# -*- coding: utf-8 -*-
"""App1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEGZm_YeVTgRnQHZ8Va9yT0KHKbAj_BV
"""

# =========================================================
# AQI STREAMLIT APPLICATION
# STREAMLIT COMMUNITY CLOUD READY
# MODEL TRAINED AT RUNTIME (NO PKL FILE)
# =========================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# ---------------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------------
st.set_page_config(page_title="AQI Dashboard", layout="wide")

# ---------------------------------------------------------
# DATA PATH
# ---------------------------------------------------------
DATA_PATH = os.path.join("output", "air_quality_dataset.csv")

# ---------------------------------------------------------
# LOAD DATA
# ---------------------------------------------------------
@st.cache_data
def load_data():
    if not os.path.exists(DATA_PATH):
        st.error("Dataset not found. Ensure output/air_quality_dataset.csv exists in the repository.")
        st.stop()

    df = pd.read_csv(DATA_PATH)
    df.columns = df.columns.str.strip()

    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

    numeric_cols = [
        "PM2.5","PM10","NO","NO2","NOx","NH3","CO",
        "SO2","O3","Benzene","Toluene","Xylene","AQI"
    ]

    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    return df

# ---------------------------------------------------------
# TRAIN MODEL (NO PKL FILE)
# ---------------------------------------------------------
@st.cache_resource
def train_model(df):
    features = [
        "PM2.5","PM10","NO","NO2","NOx","NH3","CO",
        "SO2","O3","Benzene","Toluene","Xylene"
    ]

    model_df = df.dropna(subset=features + ["AQI"])

    X = model_df[features]
    y = model_df["AQI"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    mae = mean_absolute_error(y_test, preds)
    r2 = r2_score(y_test, preds)

    return model, mae, r2

# ---------------------------------------------------------
# LOAD DATA AND TRAIN MODEL
# ---------------------------------------------------------
df = load_data()
model, mae, r2 = train_model(df)

# ---------------------------------------------------------
# SIDEBAR NAVIGATION
# ---------------------------------------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio(
    "Select Page",
    ["Home", "Data Overview", "EDA", "AQI Prediction"]
)

# =========================================================
# HOME
# =========================================================
if page == "Home":
    st.title("Air Quality Analysis and AQI Prediction")

    st.write(
        "This application provides interactive exploration of air quality data "
        "and predicts the Air Quality Index (AQI) using a Random Forest model."
    )

    st.subheader("Model Performance (Test Set)")
    st.write(f"Mean Absolute Error (MAE): {mae:.2f}")
    st.write(f"R² Score: {r2:.3f}")

# =========================================================
# DATA OVERVIEW
# =========================================================
elif page == "Data Overview":
    st.title("Dataset Overview")

    st.subheader("Dataset Preview")
    st.dataframe(df.head(10))

    st.subheader("Dataset Shape")
    st.write(f"Rows: {df.shape[0]} | Columns: {df.shape[1]}")

    st.subheader("Summary Statistics")
    st.dataframe(df.select_dtypes(include=[np.number]).describe().T)

    st.subheader("Missing Values")
    missing_df = df.isnull().sum().reset_index()
    missing_df.columns = ["Column", "Missing Count"]
    st.dataframe(missing_df)

# =========================================================
# EDA
# =========================================================
elif page == "EDA":
    st.title("Exploratory Data Analysis")

    st.subheader("AQI Distribution")
    fig, ax = plt.subplots()
    sns.histplot(df["AQI"].dropna(), kde=True, ax=ax)
    st.pyplot(fig)

    st.subheader("PM2.5 vs AQI")
    valid = df[["PM2.5", "AQI"]].dropna()
    fig, ax = plt.subplots()
    sns.scatterplot(x=valid["PM2.5"], y=valid["AQI"], alpha=0.3, ax=ax)
    st.pyplot(fig)

    st.subheader("Correlation Heatmap")
    corr_cols = [
        "PM2.5","PM10","NO","NO2","NOx","NH3","CO",
        "SO2","O3","Benzene","Toluene","Xylene","AQI"
    ]
    corr_cols = [c for c in corr_cols if c in df.columns]

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(df[corr_cols].corr(), cmap="coolwarm", ax=ax)
    st.pyplot(fig)

# =========================================================
# AQI PREDICTION
# =========================================================
elif page == "AQI Prediction":
    st.title("AQI Prediction")

    features = [
        "PM2.5","PM10","NO","NO2","NOx","NH3","CO",
        "SO2","O3","Benzene","Toluene","Xylene"
    ]

    inputs = {}
    col1, col2 = st.columns(2)

    for i, f in enumerate(features):
        if i % 2 == 0:
            inputs[f] = col1.number_input(f, min_value=0.0, value=5.0)
        else:
            inputs[f] = col2.number_input(f, min_value=0.0, value=5.0)

    if st.button("Predict AQI"):
        input_df = pd.DataFrame([inputs])
        prediction = model.predict(input_df)[0]

        st.success(f"Predicted AQI: {prediction:.2f}")

        if prediction <= 50:
            category = "Good"
        elif prediction <= 100:
            category = "Satisfactory"
        elif prediction <= 200:
            category = "Moderate"
        elif prediction <= 300:
            category = "Poor"
        elif prediction <= 400:
            category = "Very Poor"
        else:
            category = "Severe"

        st.info(f"AQI Category: {category}")